name: lint
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.4.0
      - name: lint
        run: |
          yarn
          yarn run prettier -c .
          yarn run eslint --max-warnings 0 .
