name: Lint
on:
  push:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: Run
        run: |
          yarn
          yarn run lint:check
